#!/usr/bin/env ruby

class TapDevice < Struct.new(:name)
  def exists?
    IO.readlines('/proc/net/dev').any? { |l| l =~ /\s+#{name}/ }
  end

  def create
    system "sudo tunctl -u #{ENV['USER']} -t #{name}" unless exists?
    self
  end
  
  def to_s
    name
  end
end

tap_device = TapDevice.new("tap0").create

network_options="-net nic,vlan=0 -net tap,ifname=#{tap_device},script=config/qemu-ifup,downscript=config/qemu-ifdown"

qemu_command = "qemu -enable-kvm -m 128m -drive file=dist/disk,if=ide,index=0,media=disk -soundhw es1370 #{network_options}"

puts "Run #{qemu_command}"
system qemu_command
